# Which is equivalent to
format = """
$username\
$hostname\
$directory\
$git_branch\
$status\
$character"""

# $memory_usage\
# $time\
# $python\
# $c\
# $shell\
# $cmake\

[python]
symbol = ""
pyenv_version_name = false
