# Which is equivalent to
format = """
$username\
$hostname\
$directory\
$git_branch\
$memory_usage\
$time\
$status\
$shell\
$python\
$c\
$cmake\
$character"""

[python]
symbol = ""
pyenv_version_name = false
